### ISSUE TITLE
学習ページのデザイン変更

### ISSUE THREAD

**Issue by koki037** [takuya-karatsu/self-flashcard#35]
### 概要
1. 学習ページで表示されていたIDを削除
2. ドロップダウンメニューを追加
3. ヘッダーの背景色変更

<img width="1202" alt="スクリーンショット 2023-04-01 12 05 27" src="https://user-images.githubusercontent.com/72676974/229262858-1763bd47-7e40-4059-9eb8-685bbd0d0829.png">

4. (4/1追記) 自身が作成者じゃない場合は、ドロップダウンを表示させない

**Comment by takuya-karatsu** [comment]
対応済みのため、クローズ
