### ISSUE TITLE
flashcard機能を作成する

### ISSUE THREAD

**Issue by takuya-karatsu** [takuya-karatsu/self-flashcard#6]
ユーザーが自分のflashcardを作成できるようにしたい

作成・編集・削除まで作成することを目標とするが、本issueでは作成機能(new, create)の実装を行う

**Comment by koki037** [comment]
ローカルでの環境構築完了

**Comment by koki037** [comment]
rails g controller flashcardを打ち込んだところ、下記エラーメッセージ出て対応中
An error occurred while installing mysql2 (0.5.4), and
Bundler cannot continue.

**Comment by koki037** [comment]
mysqlインストールしてpath指定して、といった設定がなされてなかったようです。解決しました

**Comment by takuya-karatsu** [comment]
下記にて対応完了のため、クローズ
https://github.com/takuya-karatsu/self-flashcard/pull/11
